# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: dart
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - src/dart.txt
      - src/dart-common.txt
      - src/dart-pubdev.txt
      - src/dart-wxyz.txt
    sort: true
