# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: ca
    sources:
      - src/ca.dic
    format: trie3
    targetDirectory: '.'
    generateNonStrict: true
checksumFile: true
