---
packages:
  - 'packages/*'
  - 'packages/*/scripts'
  - 'packages/codetypo-eslint-plugin/fixtures/import-support'
  - 'packages/codetypo-eslint-plugin/fixtures/simple'
  - 'rfc/*'
  - 'rfc/drafts/*'
  - 'test-fixtures/dictionaries/*'
  - 'test-fixtures/issues/issue-5034'
  - 'test-fixtures/issues/issue-5034/frontend'
  - 'test-packages/*/*'
  - 'test-packages/*/*/bin'
  - 'test-packages/*/*/source'
  - 'test-packages/yarn'
  - 'tools/*'
  - doc-generator
  - examples/*
  - integration-tests
  - scripts
  - website
  - codetypo-corpus/codetypo-dict-file-checker
  - codetypo-corpus/dictionaries/*
  - codetypo-corpus/dictionaries/*/scripts
  - codetypo-corpus/packages/*
  - codetypo-corpus/generator-codetypo-dicts
  - codetypo-corpus/scripts
