packages:
  - 'packages/**/*'  # Includes all subdirectories and files under packages
  - 'rfc/**/*'  # Includes all subdirectories and files under rfc
  - 'test-fixtures/**/*'  # Includes all subdirectories and files under test-fixtures
  - 'test-packages/**/*'  # Includes all subdirectories and files under test-packages
  - 'tools/*'
  - 'doc-generator'
  - 'examples/*'
  - 'integration-tests'
  - 'scripts'
  - 'website'
  - 'codetypo-dict-file-checker/*'
  - 'dictionaries/**/*'  # Includes all subdirectories and files under dictionaries
  - 'generator-codetypo-dicts'
