files:
  - '**/*.{md,txt}'
language: en,hr
import:
  - ./codetypo-ext.json
ignorePaths:
  - /src/*.{aff,dic}
ignoreWords:
  - dictman
  - engl
  - Hebdo
  - Juric
  - Kitarović
  - Kolinda
  - Lackovic
  - LGPL
  - Poklepović
  - Šebetić
  - SISSL
  - wordlist
