# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: pl_pl
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/hunspell/pl_pl.dic
      - src/additional_words.txt
    generateNonStrict: true
checksumFile: true
