# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'en-shared'
    sources:
      - src/shared-additional-words.txt
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
    excludeWordsFrom:
      - src/exclude-words.txt
