# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'ro-ro'
    sources:
      - src/additional_words.txt
      - src/hunspell/index.dic
      - src/Words-Romanian.txt
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: false
checksumFile: true
