name: Bug Report
description: Create a report to help us improve.
title: '[Bug]: '
labels: ['Needs Investigating', 'bug', 'new issue']
body:
  - type: markdown
    attributes:
      value: |
        🛑✋ This is a bug report for codetypo software. To add or remove words in a dictionary, visit [codetypo-dicts](https://github.com/khulnasoft/codetypo-dicts/issues).

        Thank you for taking the time to fill out this bug report! Please describe the issue in as much detail as possible.

        # Information

  - type: dropdown
    id: kind_of_issue
    attributes:
      label: Kind of Issue
      description: What type of issues are you having?
      multiple: true
      options:
        - Runtime - command-line tools
        - Building / Compiling
        - Security
        - Change in behavior / Regression
        - Crash / Error

  - type: dropdown
    id: component
    attributes:
      label: Tool or Library
      description: Which Tool or Library is causing the issue?
      multiple: true
      options:
        - codetypo # - the command-line spelling tool.
        - codetypo/eslint-plugin # - the plugin for ESLint.
        - codetypo-tools # - used for building dictionary files.
        - codetypo-lib # - library that does the actual spell checking.
        - codetypo-trie # - tool for working with trie files.
        - Other

  - type: input
    id: codetypo-version
    attributes:
      label: Version
      description: Which version of CodeTypo?
      placeholder: ex. 6.6.0
    validations:
      required: false

  - type: dropdown
    id: component-library
    attributes:
      label: Supporting Library
      description: Issue with supporting library?
      multiple: true
      options:
        - 'Not sure / None'
        - 'codetypo-glob' # - library for matching glob patterns."
        - 'codetypo-io' # - thin file i/o library."
        - 'codetypo-trie-lib' # - trie lib."
        - 'codetypo-trie2-lib' # - trie lib alternate format."
        - 'Other' # - one of the other libraries."

  - type: dropdown
    id: os-type
    attributes:
      label: OS
      description: Which OS has the issue?
      multiple: true
      options:
        - 'All of them'
        - 'macOS'
        - 'Linux'
        - 'Windows'
        - 'Other'

  - type: input
    id: on-version
    attributes:
      label: OS Version
      description: Which version of the OS?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Bug Description

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of what is happening. Please include screenshots and code samples as necessary.
      placeholder: Please tell us about the issue. Paste screenshots from your clipboard to upload them.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Description of the steps necessary to reproduce the behavior.
      placeholder: |
        1. Command line '...'
        2.
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    id: more-info
    attributes:
      label: Additional Information
      description: Please provide any additional information that would help to understand the issue.
      placeholder: Add any other context about the problem here.

  - type: markdown
    attributes:
      value: |
        # Configuration

  - type: textarea
    id: codetypo-json
    attributes:
      label: 'codetypo.json'
      description: Please provide a copy of your `codetypo.json` file.
      render: jsonc

  - type: textarea
    id: codetypo-yaml
    attributes:
      label: 'codetypo.config.yaml'
      description: Please provide a copy of your `codetypo.config.yaml` file.
      render: yml

  - type: input
    id: example-repository
    attributes:
      label: Example Repository
      description: An example repository makes things easier to debug.
      placeholder: https://github.com/owner/repo

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/khulnasoft/codetypo/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
