blank_issues_enabled: false
contact_links:
  - name: Add or Remove Words in a Dictionary
    url: https://github.com/khulnasoft/codetypo/issues
    about: Please suggest corrections in codetypo-dicts.
