# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json

$schema: https://raw.githubusercontent.com/khulnasofto/main/packages/codetypo-tools/codetypo-tools.config.schema.json
targets:
  - name: typescript
    targetDirectory: ./dict
    compress: false
    format: plaintext
    sources:
      - src/domGlobalEventHandlers.txt
      - src/domGlobalEvents.txt
      - src/ecosystem-terms.txt
      - src/typescript.txt
    sort: true
keepRawCase: true
