# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: et_EE
    targetDirectory: .
    compress: false
    format: trie3
    sources:
      - src/index.dic
      - src/additional_words.txt
    sort: true
    generateNonStrict: true
checksumFile: true
