# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: lorem
    targetDirectory: ./dict
    compress: false
    format: plaintext
    sources:
      - src/dictionary.txt
    sort: true
