ignorePaths:
  - '*.{ts,js}'
  - 'codetypo*.{json,yaml}'
ignoreWords:
  - quic
  - tsbuildinfo
words:
  - pnpm
flagWords:
  - blacklist->denylist
  - whitelist->allowlist
  - café->cafe
  - bluelist->greenList
  - Bluelist->GreenList
