# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

$schema: https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json
targets:
  - name: win32
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - src/generator/win32.txt
      - src/additional-terms.txt
    sort: true
keepRawCase: true
