# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'hu-hu'
    sources:
      - filename: 'src/hunspell/hu_HU.dic'
        maxDepth: 1 # This is set to 1 to prevent initial builds from taking too long.
      - filename: src/additional_words.txt
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: false
checksumFile: true
