# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

$schema: https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json
targets:
  - name: filetypes
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - src/filetypes.txt
    sort: true
