# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'pokemon'
    sources:
      - filename: 'src/pokemon.txt'
        split: true
    format: 'plaintext'
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
checksumFile: true
