# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: Czech
    sources:
      - src/Czech.dic
    format: trie3
    targetDirectory: '.'
    generateNonStrict: true
checksumFile: true
