# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'elisp'
    sources:
      - filename: 'src/elisp.txt'
        maxDepth: 1 # This is set to 1 to prevent initial builds from taking too long.
    format: 'plaintext'
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
checksumFile: true
