# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: en_CA
    sources:
      - src/additional_words.txt
      - src/aoo-mozilla-en-dict/en_CA.dic
      - src/hunspell-en_CA-large/en_CA-large.dic
      - node_modules/@codetypo/dict-en-shared/dict/shared-additional-words.txt
    format: trie3
    targetDirectory: '.'
    generateNonStrict: true
    excludeWordsFrom:
      - node_modules/@codetypo/dict-en-shared/dict/exclude-words.txt
checksumFile: true
