# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: docker-words
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - src/docker-words.txt
    sort: true
