# yaml-language-server: $schema=./../../codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: sci
    sources:
      - ./sci.txt
    format: trie3
  - name: sciV1
    sources:
      - ./sci.txt
    format: trie
