$schema: https://raw.githubusercontent.com/khulnasoft/codetypo/main/codetypo.schema.json
import:
  - ./codetypo-reporter.json
  - ./temp/chef/chef/codetypo.json

patterns:
  - name: RsaCert
    pattern: >-
      /-{5}BEGIN\s+(CERTIFICATE|(?:(?:RSA|EC)\s+)?(?:PRIVATE|PUBLIC)\s+KEY)[\w=+\-/=\\\s:,]+?-{5}END\s+\1-{5}/g

dictionaryDefinitions:
  - name: 'chef'
    path: 'https://raw.githubusercontent.com/chef/chef_dictionary/main/chef.txt'
    description: 'Custom Chef Dictionary'
