name: codetypo-action
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  codetypo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - uses: khulnasoft/codetypo-action@v6.10.0
