# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'fullstack'
    sources:
      - filename: src/fullstack.txt
        split: true
      - src/tools-and-services.txt
    format: plaintext
    targetDirectory: './dict'
    generateNonStrict: false
    compress: false
