# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: public-licenses
    targetDirectory: .
    compress: true
    format: plaintext
    sources:
      - listFile: source-files.txt
    sort: true
