# yaml-language-server: $schema=https://raw.githubusercontent.com/khulnasoft/codetypo/main/packages/codetypo-tools/codetypo-tools.config.schema.json

targets:
  - name: 'hy'
    sources:
      - filename: 'src/additional_words.txt'
      - filename: 'src/hy_AM.dic'
        maxDepth: 3
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: false
checksumFile: true
