name: codeTypo-cli
on:
  pull_request:
  push:
    branches:
      - main
  # Run on demand
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codetypo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and Pnpm
        uses: ./.github/actions/setup-node

      - # It is necessary to run `pnpm i` in order install some dictionaries.
        name: prepare-codetypo-action
        run: pnpm i
      - run: pnpm --filter @codetypo/codetypo-types --filter @codetypo/codetypo-bundled-dicts run build

      - name: Restore CodeTypo cache
        uses: actions/cache@v4.2.0
        with:
          key: codetypo-cache-v2-${{ runner.os }}-${{ hashFiles('**/*.ts', '**/*.md') }}
          path: |
            .codetypocache
          restore-keys: |
            codetypo-cache-v2-${{ runner.os }}-

      - name: codetypo@latest
        run: npx codetypo@latest --cache --cache-strategy=content --cache-location=.codetypocache --exclude="yarn2" --no-progress "**"
        # run: npx codetypo@latest --cache --cache-strategy=content --cache-location=.codetypocache --exclude="yarn2" "**"
