name: Labels

on:
  pull_request:
    types: [opened, reopened, labeled, edited, synchronize, unlabeled, closed]

jobs:
  fix-labels-on-pr:
    name: Fix labels on PR
    if: ${{ contains(github.event.pull_request.labels.*.name, 'fix') && contains(github.event.pull_request.labels.*.name, 'Update Dictionaries')  }}
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr edit "$NUMBER" --remove-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          LABELS: fix
