name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the release type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    if: contains('["khulnasoft-bot"]', github.actor)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          pip install -r requirements/requirements.txt

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Run Version Bump Script
        run: python .github/action/bump.py ${{ github.event.inputs.release_type }}

      - name: Push Changes
        run: |
          git push origin HEAD
          git push --tags
